"""Схемы раздела Создание и управление заявками на поставку FBO."""
__all__ = [
    "ClusterListRequest",
    "ClusterWarehouse",
    "ClusterLogisticCluster",
    "Cluster",
    "ClusterListResponse",
    "WarehouseFboListRequest",
    "WarehouseFboListCoordinate",
    "WarehouseFboListItem",
    "WarehouseFboListResponse",
    "WarehouseFboSellerCoordinates",
    "WarehouseFboSellerAddress",
    "WarehouseFboSellerContacts",
    "WarehouseFboSellerWorkingDay",
    "WarehouseFboSellerItem",
    "WarehouseFboSellerListResponse",
    "DraftCreateItem",
    "DraftCreateRequest",
    "DraftCreateResponse",
    "DraftCreateInfoV1Request",
    "DraftCreateInfoV1BundleId",
    "DraftCreateInfoV1WarehouseStatus",
    "DraftCreateInfoV1SupplyWarehouse",
    "DraftCreateInfoV1Warehouse",
    "DraftCreateInfoV1Cluster",
    "DraftCreateInfoV1ItemValidation",
    "DraftCreateInfoV1Error",
    "DraftCreateInfoV1Response",
    "DraftCreateInfoRequest",
    "DraftCreateInfoAvailabilityStatus",
    "DraftCreateInfoStorageWarehouse",
    "DraftCreateInfoWarehouse",
    "DraftCreateInfoCluster",
    "DraftCreateInfoRejectedItem",
    "DraftCreateInfoItemValidation",
    "DraftCreateInfoError",
    "DraftCreateInfoResponse",
    "DraftTimeslotInfoV1Request",
    "DraftTimeslotV1Slot",
    "DraftTimeslotV1Day",
    "DraftTimeslotV1Warehouse",
    "DraftTimeslotInfoV1Response",
    "DraftTimeslotInfoSelectedClusterWarehouse",
    "DraftTimeslotInfoRequest",
    "DraftTimeslotSlot",
    "DraftTimeslotDay",
    "DraftTimeslotWarehouseTimeslots",
    "DraftTimeslotInfoResult",
    "DraftTimeslotInfoResponse",
]

from .v1__cluster_list import (
    Cluster,
    ClusterListRequest,
    ClusterListResponse,
    ClusterLogisticCluster,
    ClusterWarehouse,
)
from .v1__draft_create import (
    DraftCreateItem,
    DraftCreateRequest,
    DraftCreateResponse,
)
from .v1__draft_create_info import (
    DraftCreateInfoV1BundleId,
    DraftCreateInfoV1Cluster,
    DraftCreateInfoV1Error,
    DraftCreateInfoV1ItemValidation,
    DraftCreateInfoV1Request,
    DraftCreateInfoV1Response,
    DraftCreateInfoV1SupplyWarehouse,
    DraftCreateInfoV1Warehouse,
    DraftCreateInfoV1WarehouseStatus,
)
from .v1__draft_timeslot_info import (
    DraftTimeslotInfoV1Request,
    DraftTimeslotInfoV1Response,
    DraftTimeslotV1Day,
    DraftTimeslotV1Slot,
    DraftTimeslotV1Warehouse,
)
from .v2__draft_create_info import (
    DraftCreateInfoAvailabilityStatus,
    DraftCreateInfoCluster,
    DraftCreateInfoError,
    DraftCreateInfoItemValidation,
    DraftCreateInfoRejectedItem,
    DraftCreateInfoRequest,
    DraftCreateInfoResponse,
    DraftCreateInfoStorageWarehouse,
    DraftCreateInfoWarehouse,
)
from .v2__draft_timeslot_info import (
    DraftTimeslotDay,
    DraftTimeslotInfoRequest,
    DraftTimeslotInfoResponse,
    DraftTimeslotInfoResult,
    DraftTimeslotInfoSelectedClusterWarehouse,
    DraftTimeslotSlot,
    DraftTimeslotWarehouseTimeslots,
)
from .v1__warehouse_fbo_list import (
    WarehouseFboListCoordinate,
    WarehouseFboListItem,
    WarehouseFboListRequest,
    WarehouseFboListResponse,
)
from .v1__warehouse_fbo_seller_list import (
    WarehouseFboSellerAddress,
    WarehouseFboSellerContacts,
    WarehouseFboSellerCoordinates,
    WarehouseFboSellerItem,
    WarehouseFboSellerListResponse,
    WarehouseFboSellerWorkingDay,
)
