from .core import APIConfig as SellerAPIConfig
from .methods import (
    SellerActionsAPI,
    SellerAnalyticsAPI,
    SellerApiKeyAPI,
    SellerBetaAPI,
    SellerBarcodeAPI,
    SellerBrandAPI,
    SellerCancellationAPI,
    SellerCategoryAPI,
    SellerFBSAPI,
    SellerFBOAPI,
    SellerPricesAndStocksAPI,
    SellerPricingStrategyAPI,
    SellerProductAPI,
    SellerWarehouseAPI,
    SellerFBSAssemblyLabelingAPI,
    SellerFBSDeliveryAPI,
    SellerFBSContainerAPI,
    SellerReturnsAPI,
    SellerReviewAPI,
    SellerQuestionAPI,
    SellerCertificateAPI,
    SellerChatAPI,
    SellerDeliveryAPI,
    SellerDigitalAPI,
    SellerFboSupplyRequestAPI,
    SellerInvoiceAPI,
    SellerNotificationAPI,
    SellerOrderAPI,
    SellerPassAPI,
    SellerPolygonAPI,
    SellerPostingAPI,
    SellerQuantAPI,
    SellerRFBSDeliveryAPI,
    SellerRatingAPI,
    SellerReceiptAPI,
    SellerReportAPI,
    SellerSearchQueriesAPI,
    SellerSellerActionsAPI,
    SellerFinanceAPI,
)


class SellerAPI(
    SellerActionsAPI,
    SellerAnalyticsAPI,
    SellerApiKeyAPI,
    SellerBetaAPI,
    SellerBarcodeAPI,
    SellerBrandAPI,
    SellerCancellationAPI,
    SellerCategoryAPI,
    SellerCertificateAPI,
    SellerChatAPI,
    SellerDeliveryAPI,
    SellerDigitalAPI,
    SellerFBOAPI,
    SellerFBSAPI,
    SellerFBSAssemblyLabelingAPI,
    SellerFBSContainerAPI,
    SellerFBSDeliveryAPI,
    SellerFboSupplyRequestAPI,
    SellerFinanceAPI,
    SellerInvoiceAPI,
    SellerNotificationAPI,
    SellerOrderAPI,
    SellerPassAPI,
    SellerPolygonAPI,
    SellerPostingAPI,
    SellerPricesAndStocksAPI,
    SellerPricingStrategyAPI,
    SellerProductAPI,
    SellerQuantAPI,
    SellerQuestionAPI,
    SellerRFBSDeliveryAPI,
    SellerRatingAPI,
    SellerReceiptAPI,
    SellerReportAPI,
    SellerReturnsAPI,
    SellerReviewAPI,
    SellerSearchQueriesAPI,
    SellerSellerActionsAPI,
    SellerWarehouseAPI,
):
    """
    Основной класс для работы с Seller API Ozon.
    Объединяет все доступные методы API в единый интерфейс.
    """
    pass

__all__ = ["SellerAPI", "SellerAPIConfig"]

